export const RESTAURANTS = [
  {
    id: 0,
    featured: true,
    name: "de Fuego",
    image: "../assets/images/deguegoSz.jpg",
    altImg: "../assets/images/defuegopool.jpg",
    carousel1: "../assets/images/defuegofoodoffering.png",
    carousel2: "../assets/images/defuegolunchspread.jpg",
    carousel3: "../assets/images/defuegobrunchfood.png",
    carousel4: "../assets/images/brazilian-salmon-bowl.jpg",
    description: "South American tapas & parilla restaurant.",
    website: "https://www.defuegogrille.com/",
  },
  {
    id: 1,
    featured: false,
    name: "Hayden's Lakefront Grill",
    image: "../assets/images/Haydenslittle.jpg",
    altImg: "../assets/images/HaydenslakeSz.jpg",
    carousel1: "../assets/images/haydenbeefplate.jpg",
    carousel2: "../assets/images/haydensandwich.jpeg",
    carousel3: "../assets/images/haydenssalad.jpg.jpeg",
    carousel4: "../assets/images/haydensSalmonfood.jpeg.jpeg",
    description: "Family friendly, casual fine dining on a lake!",
    website: "https://www.haydensgrill.com/",
  },
  {
    id: 2,
    featured: false,
    name: "Stone Cliff Inn",
    image: "../assets/images/stonecliffSz.jpg",
    altImg: "../assets/images/stonecliffback.jpg",
    carousel1: "../assets/images/Stone_Cliff_395.jpg_",
    carousel2: "../assets/images/Stone_Cliff_fishfood.jpg",
    carousel3: "../assets/images/Stone_Cliff_foodplate.jpg",
    carousel4: "../assets/images/stonecliffupstairs.jpg",
    description: "A rustic inn off the Clackamas River.",
    website: "https://www.stonecliffinn.com/",
  },
  {
    id: 3,
    featured: false,
    name: "Shigezo",
    image: "../assets/images/ShigezoSz.jpg",
    altImg: "../assets/images/shigezocarousel.png",
    carousel1: "../assets/images/shigezocarousel1.jpg",
    carousel2: "../assets/images/shigezocarousel2.jpg",
    carousel3: "../assets/images/shigezocarousel3.jpg",
    carousel4: "../assets/images/shigezocarousel4.jpg",
    description: "Japanese sushi & izakaya bar.",
    website: "https://www.shigezo-pdx.com/",
  },
  {
    id: 4,
    featured: false,
    name: "Southpark Seafood Grill",
    image: "../assets/images/southparkSz.jpeg",
    altImg: "../assets/images/southparkmedium.jpeg",
    carousel1: "../assets/images/Southparkplate.jpeg",
    carousel2: "../assets/images/southparkseafoodspread.jpeg",
    carousel3: "../assets/images/southparkseafoodcounter.jpeg",
    carousel4: "../assets/images/southparkseafoodstew.jpeg",
    description: "High quality seafood grill in the heart of downtown Portland",
    website: "https://southparkseafood.com/",
  },
  {
    id: 5,
    featured: false,
    name: "Le Chon",
    image: "../assets/images/lechonSz.jpg",
    altImg: "../assets/images/lechondiningroom.jpg",
    carousel1: "../assets/images/lechonburger.jpg",
    carousel2: "../assets/images/lechonfishplate.jpg",
    carousel3: "../assets/images/lechonfood.jpg",
    carousel4: "../assets/images/lechonfoodoutside.jpg",
    description: "South American Tapas restaurant downtown Portland",
    website: "https://lechonpdx.com/",
  },
];
