export const RESTAURANTS_LOADING = 'RESTAURANTS_LOADING';
export const RESTAURANTS_FAILED = 'RESTAURANTS_FAILED';
export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';

export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUESTS = 'ADD_REQUESTS';
export const REQUESTS_FAILED = 'REQUESTS_FAILED';

export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_FAILED = 'SERVICES_FAILED';
export const ADD_SERVICES = 'ADD_SERVICES';

export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_FAILED = 'CONTACT_FAILED';
export const ADD_CONTACT = 'ADD_CONTACT';


export const RESTAURANTSFL_LOADING = 'RESTAURANTSFL_LOADING';
export const RESTAURANTSFL_FAILED = 'RESTAURANTSFL_FAILED';
export const ADD_RESTAURANTSFL = 'ADD_RESTAURANTSFL';

export const EXAMPLES_LOADING = "EXAMPLES_LOADING";
export const EXAMPLES_FAILED = 'EXAMPLES_FAILED';
export const ADD_EXAMPLES = 'ADD_EXAMPLES';


// export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_SUCCESS = 'LOGING_SUCCESS';
// export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

